name: flush
version: 1.0.0+1

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluro: ^1.5.0
  flutter_bloc: ^0.20.0
  flutter_camera_ml_vision: ^1.0.0
  dio: ^2.1.13
  flutter_icons: ^0.1.4
  # QRCode Generate
  # qr_flutter: ^2.1.0+55
  # QRCode Scanner
  # qr_utils: ^0.1.4 # works fine but cannot custom ui
  barcode_scan: ^1.0.0 # 
  # qrcode_reader: ^0.4.4 # Not working
  # fast_qr_reader_view: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"